### ISSUE TITLE
Run keeps saying Port '1234' is already in use by another process

### ISSUE THREAD

**Issue by popkutty** [pact-foundation/pact-js#136]
## Software versions

* **OS**: e.g. Windows 10
* **Node Version**: v6.11.0
* **Pact Version**:  "4.3.1"

## Expected behaviour

My test to be run

## Actual behaviour

Test is not starting at all

## Steps to reproduce
I just have `"pact":"^4.0.0"` in my package.json

## Relevant log files
C:\Users\user\pact\pact-runner> mocha --timeout 23000 .\contractgen\sotest.contract.gen.js
[2017-12-12T21:41:36.083Z]  INFO: pact-node@6.5.0/12720 on C659470EE591A8:
    Creating Pact Server with options:
    port = 1234,
    log = C:\Users\user\pact\pact-runner\logs\mockserver-integration.log,
    dir = C:\Users\user\pact\pact-runner\pacts,
    spec = 1,
    ssl = false,
    cors = false,
    host = localhost,
    pactFileWriteMode = overwrite

  Pact
[2017-12-12T21:41:36.150Z]  INFO: pact-node@6.5.0/12720 on host: Created 'platforms\win32\bin\pact-mock-service.bat service --port '1234' --log 'C:\Users\user\pact\pact-runner\logs\mockserver-integration.log' --
act_dir 'C:\Users\user\pact\pact-runner\pacts' --pact_specification_version '1' --host 'localhost' --pact-file-write-mode 'overwrite'' process with PID: 15060
[2017-12-12T21:41:38.750Z] ERROR: pact-node@6.5.0/12720 on host: Port '1234' is already in use by another process.
[2017-12-12T21:41:43.515Z]  INFO: pact-node@6.5.0/12720 on host: Removing all Pact servers.
Terminate batch job (Y/N)?

**Comment by bethesque** [comment]
Looks like the mock service from the previous run is not being shut down properly on windows. I'm no windows expert, but if it's asking "Terminate batch job (Y/N)" and there's no way of inputting a "Y", I don't think it gets shut down properly. I'm not sure why you're encountering this problem now, as I'm sure we've had windows users before. Thoughts @mboudreau and @mefellows?

As a work around, you'll need to search for the process using the command prompt or windows process monitor, and kill it manually.

**Comment by mefellows** [comment]
As @bethesque said, the error is pretty clear. It would be great if you could find out if the process from each pact run is not shutting down the mock service correctly, as if that's the case we have a defect.

As an aside, if you don't specify the port, we will allocate a random available port. This is ideal for CI type environments where you can't guarantee a port is available at runtime.

**Comment by mefellows** [comment]
@popkutty could you also please let us know if you're running this in Powershell or cmd, and if you get the same behaviour in each?

**Comment by popkutty** [comment]
@mefellows @bethesque  I cannot find a process using port 1234 after I shut the process down. I tried to run from powershell and cmd prompt. It was working before with older version. I updated to new, and getting this error

**Comment by popkutty** [comment]
Here is my code

```
describe('Pact', () => {
    let provider;

    // Configure mock server
    const mockServer = wrapper.createServer({
        port: 1234,
        log: path.resolve(process.cwd(), 'logs', 'mockserver-integration.log'),
        dir: path.resolve(process.cwd(), 'pacts'),
        spec: 1
    });


    before((done) => {

        // Start mock server
        mockServer.start().then(() => {
            provider = Pact({ consumer: 'SOApp', provider: 'api.stackexchange', port: 1234 });

            provider.addInteraction({
                state: 'Get Question',
                uponReceiving: 'a request for question',
                withRequest: {
                    method: 'GET',
                    path: '/2.2/questions/45204710',
                    query: {order: 'desc', sort:'activity', site:'stackoverflow'}
                },
                willRespondWith: {
                    status: 200,
                    headers: { 'Content-Type': 'application/json' },
                    body:
                    {
                        "items": [
                            {
                                "tags": eachLike('java,spring,spring-security'),
                                "owner": {
                                    "reputation": term({
                                        matcher: '[^\d]',
                                        generate: "123"
                                      }),
                                    "user_id": 2104638,
                                    "user_type": "registered",
                                    "accept_rate": 51,
                                    "profile_image": "https://i.stack.imgur.com/EUbux.jpg?s=128&g=1",
                                    "display_name": "Pasupathi",
                                    "link": "https://stackoverflow.com/users/2104638/pasupathi"
                                },
                                "is_answered": true,
                                "view_count": 143,
                                "accepted_answer_id": 45204790,
                                "answer_count": 1,
                                "score": 2,
                                "last_activity_date": 1500522560,
                                "creation_date": 1500522062,
                                "question_id": 45204710,
                                "link": "https://stackoverflow.com/questions/45204710/disable-spring-security-for-post-method",
                                "title": "Disable spring security for POST method"
                            }
                        ],
                        "has_more": false,
                        "quota_max": 300,
                        "quota_remaining": 290

                    }

                }
            }).then(() => done())
        })
    });



    it('Verify color object has correct properties', (done) => {

        httpClient.get('http://localhost:1234/2.2/questions/45204710?order=desc&sort=activity&site=stackoverflow').then(function (res) {
        done();
        });

    });


    after(() => {
        // Write pact files
        provider.finalize().then(() => {
            wrapper.removeAllServers()

        }).catch(function(res) {
            console.log(res)
        });
    });
});
```

**Comment by popkutty** [comment]
When I change this line from 

pact-foundation/pact-node/src/pact.js L25
`if (options && options.port && _.some(this.__servers, function (s) { return s.options.port === options.port; })) {` 
to
`if (options && options.port && _.some(this.__servers, function (s) { return false; })) {`

Working fine. Is there something needs to be fixed.

But server is not getting closed

```
{ Error: Couldn't stop Pact with PID '-1'
    at Timeout._onTimeout (C:\Users\pxr8273\pact\pact-runner\node_modules\q\q.js:1843:21)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) code: 'ETIMEDOUT' }
```

**Comment by bethesque** [comment]
Can you provide a repository with some example code so that the maintainers can reproduce the issue please.

**Comment by popkutty** [comment]
@bethesque  I gave my entire test code above 2 comments.

**Comment by mefellows** [comment]
Hi @popkutty, that's just your mocha test - we'll need a reproducible project we could run on a windows machine (so things like `package.json` and how your run your tests).

i.e. we should be able to do the following and reproduce your issue:

```
git clone <Your project>
npm i
npm t
```

**Comment by mluiten** [comment]
I'm having this issue as well, here's a project that reproduces this issue (on Windows 7, node 8.9.4): https://github.com/mluiten/pact-issue-136 

Seems that version 4.2.1 does not have this issue.

**Comment by mefellows** [comment]
Thanks @mluiten, I have created an appveyor build and reproduced the issue: https://ci.appveyor.com/project/mefellows/pact-issue-136/build/1.0.2.

Now to find the source of the bug!

**Comment by mefellows** [comment]
OK @mluiten, I've gone through your example code base to see if we can identify the issue, but found that your code uses Pact in a bit of a strange way.

1. You are using an older Pact version, I'd suggest you upgrade to the latest `5.x.x` (4.x.x is technically still supported, but we will be deprecating it soon)
1. For some reason you are calling the `pact-node` APIs directly - this is not necessary and is possibly the cause of your problems (as now Pact JS is unable to manage all of the state). 

For most intents and purposes, `pact-node` is really not for external consumption and should be wrapped by libraries like Pact, at least for the use cases we're talking about (it does have a useful CLI and some other publishing features). It is really part of the engine behind the DSL.

Here is my [example](https://github.com/mefellows/pact-issue-136/blob/master/test/pacts.js). It is hardly idiomatic test code, but is the minimum changes required to uplift the example you provided.

Here is the [Appveyor build](https://ci.appveyor.com/project/mefellows/pact-issue-136) demonstrating Pact working correctly - in this case it's a failed build, but that's because we expect interactions and don't make any API calls. Importantly, it starts the mock server and interacts with it.

I'll leave this open in case I've done something completely silly, but AFAICT, there is no bug here.

**Comment by mboudreau** [comment]
@mluiten It sound like you're just trying to spin up several versions of pact node on the same port, hence the port conflict.  Make sure you you stop/delete the service after each test.  But yeah, I'd totally go with what @mefellows is saying and just use pact-js to do all the work for you.

**Comment by mefellows** [comment]
OK so I was annoyed/curious and thought it would be good to get to the bottom of why it wasn't working, and it was obvious.

1. [Here](https://github.com/mefellows/pact-issue-136/tree/feat/pact-4.x.x) is a working `4.x.x` version of that example code
1. [Here](https://ci.appveyor.com/project/mefellows/pact-issue-136/build/1.0.5) is the appveyor build that shows it working (failed tests, but working pact)

Basically, you started the mock server manually, but never called the `setup()` function on the `provider` (the `Pact` object), which is responsible for ensuring everything is up and going before allowing the contract tests to happen (which issue http requests to the mock server, amongst other things). This behaviour may have changed over pact versions as how internal state is managed may have changed, but you're seeing the issue because you're coordinating the server outside of Pact JS's knowledge.

Hope this helps 👍 .

**Comment by Parbinder** [comment]
Just to add, I hope this might be helpful, I've recently implemented CDC using Pact for my organization (Thank you guys, Pact is awesome 😉). If you want to use a dynamic port at runtime, I've implemented that as given below (syntax-Typescript). 

`    /**
     * Creates an instance of Provider 
     * @param provider Name of the provider
     * @param consumer Name of the consumer
     * @param targetdirectory Relative path to the directory where Pact file will be generated 
     * @returns `Pact`
     */
    private getProvider = (provider_name: string, consumer_name: string, target_directory:string):Pact =>
    {
        return new Pact
            ({
                logLevel: "fatal",
                consumer: consumer_name,
                provider: provider_name,
                port: 0,
                dir: target_directory,
                log: INTERACTION_LOG_PATH,
                spec: 2,
                host: "localhost",
                pactfileWriteMode: "overwrite"
            })
    }

    /**
     * Fetches the port assigned to the mock server dynamically by the Operating system
     * @returns `number` Port number assigned to provider
     */
    private getMockServicePort = ():number =>  
    {
        return this.provider.opts.port
    }`

So, if you pass the 'port' with value '0', then the Operating system should itself assign a free random port to your provider instance, and then before sending a request to the mocked server, you can simply fetch it from your provider instance

**Comment by mefellows** [comment]
(I've just tidied up your code to aid readability @Parbinder).

You don't need to set the port to `0`, you can just omit it completely.

You can then extract it after the `provider.setup()` which returns the configuration for the server:  https://github.com/pact-foundation/pact-js/blob/master/examples/e2e/test/consumer.spec.js#L87-L92

**Comment by truonghongtrieu** [comment]
Hi all, it seems to be a memory leak issue of pact since the mock server didn't shutdown after the test has finished. I doubt that using random ports is a good option.

My mock server setup is like this:
```
  const mockService = new Pact({
    consumer: 'ContentGatewayPactService',
    provider: 'ContentJobPactService',
    host: 'localhost',
    port: 7200,
    cors: true,
    logLevel: 'debug',
    log: path.resolve(process.cwd(), 'logs', 'pact.log'),
    dir: path.resolve(process.cwd(), 'pacts'),
  });
```

I can still see the process running on the given port by `netstat -an | grep LISTEN | grep 7200`.

I couldn't find any api documentation to manually shutdown the server, so I used process.exit timeout as a workaround, it works for me but I think this should be fixed in the pact lib: `setTimeout(() => process.exit(), 1000);`

**Comment by mefellows** [comment]
Are you calling `finalize()`? That should shut the process down and save your pacts.

You can [shut down](https://github.com/pact-foundation/pact-js-core/#remove-all-mock-servers) the servers, but it should not be necessary (yes, that's not documented in pact-js but it's definitely not something that should need to be done normally).

**Comment by truonghongtrieu** [comment]
Thanks @mefellows ,

Turns out it was the jest hook timeout of `beforeAll` and `afterAll` that terminated the process and caused the `finalize()` not being called, hence the server was not shutdown. I've fixed my code, which connects to the broker for the test to complete in 5-8 seconds. and it works now. 

```
  beforeAll(async () => {
    jest.setTimeout(1000);
    const opts = await mockService.setup(); //start the Mock Server and wait for it to be available.
    const apiUrl = `http://${opts.host}:${opts.port}`;

    const httpService = new HttpService({ apiUrl: apiUrl });

  }, 15000); // wait for 15s max if the jest hook needs more than 5s for pact
```

Thanks for the removeAllServers() method and your prompt help!

**Comment by mefellows** [comment]
Ah, glad to hear you found the issue - you're welcome!

**Comment by TimothyJones** [comment]
You might be interested in the wrapper that does all this for you: `jest-pact`
